package com.Tancem.PIS.model.bagsType;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.sql.Timestamp;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class BagsType {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bags_type_seq")
    @SequenceGenerator(name = "bags_type_seq", sequenceName = "bags_type_seq", allocationSize = 1)
    private int id;



    private String types_Of_Bags;


    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Timestamp createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private Timestamp updatedAt;


    @Column(name="in_Active",nullable = false)
    private boolean inActive=true;

    // Getters and Setters will be automatically generated by @Data present in Lombok
}
